import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    container:{
        flexDirection:'row',
        width:'95%',
        alignItems:"center",
        gap:8,
        marginBottom:8,
        marginHorizontal:16
    },
    name:{
        backgroundColor:'#ffffff20',
        padding:16,
        color:'#fff',
        width:'80%',
        fontSize:16
    },
    buttonText:{
        fontSize:32,
        color:'#fff'
    },
    button:{
        width:48,
        height:48,
        borderRadius:8,
        backgroundColor:'#E23C44',
        justifyContent:'center',
        alignItems:'center'
    }
})